# Copyright (c) 2014 steak - All rights reserved

# please do not edit this file
# set the file config_prod.py in the same directory to change default value

# GIT version of the current code
version = "dev"

# the name of the database to use
database_name = "house.db"

# the port of the rpc service
tasker_rpc_port = 8002

# logging system
import logging.config
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s.%(levelname)s %(name)s: %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level':'DEBUG',
            'class':'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        '': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': True
        },
        # do not log the debug of peewee, it's very verbose
        'peewee': {
            'handlers': ['default'],
            'level': 'WARNING',
            'propagate': True
        }
    }
})
